spring.application.name=skillcart-backend

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/skillcart}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET:skillcart_super_secret_key_2026_make_it_long_and_safe}
jwt.expiration=${JWT_EXPIRATION:86400000}

razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_T8F1O9c2ekamBT}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:k5j6er0hRRGG6wbZys7hHdfI}

admin.name=${ADMIN_NAME:Admin}
admin.email=${ADMIN_EMAIL:admin@skillcart.com}
admin.password=${ADMIN_PASSWORD:admin123}

app.seed.demo-courses=${SEED_DEMO_COURSES:true}

frontend.url=${FRONTEND_URL:http://localhost:5173}
