import api from './axios'
export const getDashboard = () => api.get('/api/admin/dashboard').then(r => r.data)
export const getAdminCourses = () => api.get('/api/admin/courses').then(r => r.data)
export const getAdminCourseDetail = (id) => api.get(`/api/admin/courses/${id}`).then(r => r.data)
export const createCourse = (data) => api.post('/api/admin/courses', data).then(r => r.data)
export const updateCourse = (id, data) => api.put(`/api/admin/courses/${id}`, data).then(r => r.data)
export const deleteCourse = (id) => api.delete(`/api/admin/courses/${id}`).then(r => r.data)
export const addLesson = (courseId, data) => api.post(`/api/admin/courses/${courseId}/lessons`, data).then(r => r.data)
export const updateLesson = (lessonId, data) => api.put(`/api/admin/lessons/${lessonId}`, data).then(r => r.data)
export const deleteLesson = (lessonId) => api.delete(`/api/admin/lessons/${lessonId}`).then(r => r.data)
export const addSection = (courseId, data) => api.post(`/api/admin/courses/${courseId}/sections`, data).then(r => r.data)
export const updateSection = (sectionId, data) => api.put(`/api/admin/sections/${sectionId}`, data).then(r => r.data)
export const deleteSection = (sectionId) => api.delete(`/api/admin/sections/${sectionId}`).then(r => r.data)
export const addLessonToSection = (sectionId, data) => api.post(`/api/admin/sections/${sectionId}/lessons`, data).then(r => r.data)
